### ISSUE TITLE
Tag links on the blog are broken (404 error)

### ISSUE THREAD

**Issue by VPetukhov** [JEFworks/JEFworks.github.io#4]
![screenshot_20180812_112700](https://user-images.githubusercontent.com/6990194/44003605-fe78a1fa-9e22-11e8-85f1-890d091609c9.png)

**Comment by JEFworks** [comment]
Thanks for the catch Viktor! Addressed in commit f9ddb09

**Comment by VPetukhov** [comment]
Thanks, Jean!
